### PR TITLE
Fixing #43

### PR DESCRIPTION
**Pull request by mikaelhg**
Add changes for fixing the bug to this PR.

### CODE REVIEW

**Comment by mikaelhg** [comment]
@Loki-Afro, what's your vote? Fix the regex, or transition from the URL parser regex to a JavaCC / ANTLR grammar?

**Comment by Loki-Afro** [comment]
Uh ANTLR sounds great! But the easy way would be fixing the regex I guess ;)

**Comment by kleinron** [comment]
I don't understand something..
The expected behavior, IMO, should be... exactly as it was.
The hash character is the delimiter for the fragment part, and the fragment part is the last part on a URL?
Or am I missing something?

**Comment by mikaelhg** [comment]
@kleinron I'll take that as a signal to reread the RFC before proceeding. It's been a couple years since I last touched that code.

**Comment by Loki-Afro** [comment]
maybe as a sidenode here, its that hash from an angular 2 website...

**Comment by mikaelhg** [comment]
Good catch @kleinron, that'll teach me to not read tickets late at night. I thought the ticket was about a broken regex leaking query parameters from the fragment to the URL query part.

**Comment by mikaelhg** [comment]
WONTFIX

**Pull request closed without merging**
